main/urls.py
from django.urls import path
from main.views import add_product_ajax, delete_product, dropdown_user, get_product_json, preview_product, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register #sesuaikan dengan nama fungsi yang dibuat
from main.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from main.views import logout_user
from main.views import increment_amount, decrement_amount
from main.views import edit_product
from main.views import create_product_flutter


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('preview_product/', preview_product, name='preview_product'),
    path('login/', login_user, name='login'), 
    path('logout/', logout_user, name='logout'),
    path('delete-product/<int:product_id>/', delete_product, name='delete_product'),
    path('increment-amount/<int:product_id>/', increment_amount, name='increment_amount'),
    path('decrement-amount/<int:product_id>/', decrement_amount, name='decrement_amount'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('dropdown_user/', dropdown_user, name='dropdown_user'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),



]

task2_inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no = models.AutoField(primary_key=True)
    date = models.DateField(auto_now_add=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.PositiveIntegerField(default=0)
    amount = models.PositiveIntegerField(default=0)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = [ "no", "name", "description", "price", "amount"]

main/views.py
import datetime
import json
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    context = {
        'products': products,
        'name': request.user.username,
        'last_login': request.COOKIES.get('last_login', 'No last login information available'),

        }

    return render(request, "main.html", context)

def preview_product(request):
    products = Product.objects.filter(user=request.user)
    context = {
        'products': products,
        'name': request.user.username,
        'last_login': request.COOKIES.get('last_login', 'No last login information available'),

        }

    return render(request, "preview_product.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)
    products = Product.objects.filter(user=request.user)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.current_stock = product.amount
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'products': products,
        'form': form,
        'name': request.user.username,
        'last_login': request.COOKIES.get('last_login', 'No last login information available'),
}
    return render(request, "create_product.html", context)


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username taken')
                return redirect('main:register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                messages.success(request, 'Your account has been successfully created!')
                return redirect('main:login')

        else:
            messages.info(request, 'Password not matching..')
            return redirect('main:register')
    else:
        return render(request, 'register.html')
        
def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('main:login')


def dropdown_user(request):
    products = Product.objects.filter(user=request.user)
    context = {
        'products': products,
        'name': request.user.username,
        'last_login': request.COOKIES.get('last_login', 'No last login information available'),

        }

    return render(request, "dropdown_user.html", context)


from django.shortcuts import get_object_or_404

def delete_product(request, product_id):
    # Get the product by its ID or return a 404 if not found
    product = get_object_or_404(Product, pk=product_id)

    # Check if the user has permission to delete the product
    if request.user == product.user:
        # Delete the product
        product.delete()
        # Redirect to the main page or any other appropriate page
        return HttpResponseRedirect(reverse('main:show_main'))
    else:
        # Return a response indicating the user doesn't have permission
        return HttpResponse("You do not have permission to delete this product.")


from django.shortcuts import get_object_or_404, redirect
from main.models import Product

def increment_amount(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    # Check if the user has permission to update the product
    if request.user == product.user:
        product.amount += 1
        product.date = (datetime.datetime.now())
        product.save()
    
    return redirect('main:show_main')

def decrement_amount(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    # Check if the user has permission to update the product
    if request.user == product.user and product.amount > 1:
        product.amount -= 1
        product.date = (datetime.datetime.now())
        product.save()
    
    elif product.amount<=1:
        product.delete()

    return redirect('main:show_main')

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)
    products = Product.objects.filter(user=request.user)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'products': products,
        'form': form,
        'name': request.user.username,
        'last_login': request.COOKIES.get('last_login', 'No last login information available'),

        }
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, price=price, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price =int(data["price"]),
            amount = int(data["amount"]),
            description = data["description"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/dropdown_user.html
{% extends 'base.html' %} 

{% block content %}

                <a href="{% url 'main:show_main' %}" style="display: flex;  padding: auto; width: auto; justify-content: center; align-items: center; position: fixed;">
                    


                <div class="dropdown-user" style=" display: flex; position: fixed; flex-direction: column; padding-block: 12px; border-radius: 20px; border-color: #f0f0f0; border-style: solid; border-width: 2px; margin-block: 30px; align-items: flex-end; margin-top: 112px; background-color: #ffffff;min-width: 10%; max-width: 5%; margin-left: 86%; margin-right: 100%; justify-content: center; align-items: center; flex-wrap: wrap;">
                        <a href="" style="text-decoration: none; background-color: #ffffff;">
                            <button style="background-color: #ffffff; display: flex; color: #888888;  text-decoration: none;">
                                <i class="fa fa-user" aria-hidden="true" style="background-color: #ffffff; color: #0195eb; margin: 4px;"></i>
                                Profil Saya
                            </button>
                        </a>
                        <a href="{% url 'main:logout' %}" style="background-color: #ffffff; ">
                            <button style="background-color: #e24c1d; color: #ffffff; width: 100%;">
                                Logout
                            </button>
                        </a>
                    </div>

                </a>
               
<!-- 
                <a href="{% url 'main:show_main' %}" style="display: flex; position:absolute; padding-top: 120px;  flex-direction: row-reverse; justify-content: space-between;text-decoration: none;">

                <div class="nav-sub" style="margin-right: 5%; min-width: 100%; max-width: 5%; display: flex;flex-direction: row-reverse; text-decoration: none;">
                    <button style="background-color: #e24c1d; color: #ffffff; margin-left: 5%; text-decoration: none;">
                        Logout
                    </button>
                    
                </div>
                </a> -->
                    
    <div style="height: 100%; ">
        {% include 'main.html' %}</div>
    {% endblock content %}

main/templates/edit_product.html
{% extends 'base.html' %} 

{% block content %}

        <div style="box-sizing: border-box; padding-block: 200px; position: fixed; width: 100%; margin: -8px;  align-items: center; display: flex; flex-direction: column; border-style: none; background-color: rgba(102, 102, 102, 0.5);  margin: 0, auto; ">
            
            <form method="POST" class="form-add" style="background-color: #f1f1f1; display: flex; justify-content: center; padding: 40px; border-radius: 60px; flex-direction: column; ">
                
                <h1 class="add-new-prod" style="display: flex; justify-content: center; align-items: center; background-color: #f1f1f1;">Edit Product</h1>{% csrf_token %}
                {{ form.as_table }}

                <div style="background-color: #f1f1f1; display: flex; flex-direction: column;">
                <td style="background-color: #0195eb;"><input class="btn" type="submit" value="Edit Product" style="width: 100%; align-items: center; color: white; background-color: #0195eb;margin-top: 40px; margin-bottom: 8px;"></td>
                <button style=" align-items: center; color: white; background-color: white; display: flex;  margin-bottom: 8px; justify-content: center;">
                    <i class="fa fa-chevron-left" aria-hidden="true" style="color: #0195eb; background-color: white; padding: 4px;"></i>
                    <a href="/" style="text-decoration: none; color: black; background-color: #ffffff;">Kembali</a>
                </button>
                </div>
                </form>
                
        </div>

<div style="height: 100%; ">
    {% include 'main.html' %}</div>
    


{% endblock %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<body>
    
<div class="padding">
    <nav class="fullnav" >
        <div class="menu-icon">
            <i class="fa fa-bars" aria-hidden="true" style="background-color: #ffffff; padding: 8px; border-radius: 12px; border-width: 2px; border-style: solid; border-color: rgb(241,241,241);" ></i>
        </div>
        <div class="logo">
            <!-- <img src="https://th.bing.com/th/id/R.6ad0fe976be696c1e6804c26a0b24e0c?rik=JF21H%2feXmlfXnQ&riu=http%3a%2f%2fmudvex.com%2fwp-content%2fuploads%2f2019%2f10%2flogo-12.png&ehk=H7KtZPbx18fPDvYg3nX7AfQ7vWFeNpZ9RcNSdNRKKrI%3d&risl=&pid=ImgRaw&r=0" alt="logo-brand"> -->
            <i class="fa-solid fa-cat" style="color: #ffffff; padding: 8px; border-radius: 8px; background-color: #e24c1d; margin-right: 8px;"></i>
            <p class="name">Mumu</p>
            <p class="name" style="color: #0195eb; font-weight: 800;">Miaw</p>
        </div>
        <div class="menu">
            <section class="menu-content">
                <a class="primary" href="{% url 'main:show_main' %}">Database</a>
                <a class="secondary" href="{% url 'main:preview_product' %}">Preview Pengguna</a>
            </section>
            <i class="fa-solid fa-bell" style="color: rgb(226, 76, 29); background-color: white;"></i>
            <span class="vertical-line">|
            </span>
            <a href="{% url 'main:show_main' %}" style="display: flex; flex-direction: row; text-decoration: none; justify-content: space-between; align-items: center; background-color: #ffffff; color: black; width: 0%; height: 0%; margin-right: 20px;">
            <div style="display: flex; flex-direction: column; background-color: #ffffff;">

                <a href="{% url 'main:show_main' %}" style="display: flex; flex-direction: row; text-decoration: none; justify-content: space-between; align-items: center; background-color: #ffffff; color: black; width: 100%;">
                <div class="profile" style="width: 72%; display: flex; background-color: #ffffff;">
                    
                    <p class="user" style="background-color: white;">{{ name }}</p>
                    <a href="{% url 'main:dropdown_user' %}" style="display: flex; flex-direction: row; text-decoration: none; justify-content: space-between; align-items: center; background-color: #ffffff; color: black; width: 0%; height: 0%; margin-right: 20px;">
                    <i id="chevron" class="fa-solid fa-chevron-down" style="position: absolute; color: #b4b4b4; background-color: white; color: black; background-color: white;"></i>
                    
                    
                    <!-- <div class="dropdown-user" style="position: absolute; background-color: #ffffff; height: 172px; min-width: 0px; max-width: 400px; margin-top: 280px; margin-left: -100px; border-radius: 20px; border-color: #f0f0f0; border-style: solid; border-width: 2px; visibility: hidden;">
                        <a href="" style="background-color: #ffffff; width: 100%; justify-content: center;">
                            <button style="background-color: #ffffff; color: #888888; margin: 12px; justify-content: center; align-items: center; width: 86%; font-weight: 600; margin-right: 16px; justify-content: space-between;">
                                <i class="fa fa-user" aria-hidden="true" style="background-color: #ffffff; color: #0195eb; margin: 8px;"></i>
                                Profil Saya
                            </button>
                        </a>
                        <a href="{% url 'main:logout' %}" style="background-color: #ffffff; width: 100%; ">
                            <button style="background-color: #e24c1d; color: #ffffff; margin: 12px; justify-content: center; align-items: center; width: 88%;">
                                Logout
                            </button>
                        </a>
                    </div> -->
                    </a>
                
                </div>
                </a>
                <!-- <div class="dropdown-user" style="position: absolute; background-color: #ffffff; height: 172px; min-width: 40px; max-width: 400px; margin-top: 80px; margin-left: -100px; border-radius: 20px; border-color: #f0f0f0; border-style: solid; border-width: 2px; visibility: hidden;">
                    <a href="" style="background-color: #ffffff; width: 100%; justify-content: center;">
                        <button style="background-color: #ffffff; color: #888888; margin: 12px; justify-content: center; align-items: center; width: 86%; font-weight: 600; margin-right: 16px; justify-content: space-between; visibility: hidden;">
                            <i class="fa fa-user" aria-hidden="true" style="background-color: #ffffff; color: #0195eb; margin: 8px;"></i>
                            Profil Saya
                        </button>
                    </a>
                    <a href="{% url 'main:logout' %}" style="background-color: #ffffff; width: 100%; visibility: hidden;">
                        <button style="background-color: #e24c1d; color: #ffffff; margin: 12px; justify-content: center; align-items: center; width: 88%;">
                            Logout
                        </button>
                    </a>
                </div> -->
            </div>
        </div>
        
    </nav> 
    </div>

    <div class="container">
        <div class="title-addproduct">
            <div class="head">
                <div class="head-content">
                    <h5 style="font-weight: 500; color: #b4b4b4; background-color: #f1f1f1; display: flex; margin: 0; margin-bottom: 40px; width: auto;">Sesi terakhir login: {{ last_login }}</h5>

                    <h1 class="container-title">Produk Tersedia</h1>
                    <p class="container-desc">Produk yang masih ada dalam inventori berjumlah {{ products|length }}.</p>
                </div>
                <div class="primary-button">
                <a class="button" href="{% url 'main:create_product' %}">
                    <button>
                        Add New Product
                        <i class="fa fa-plus" aria-hidden="true" style="color: #0195eb; background-color: #ffffff; padding: 4px;"></i>
                    </button>
                </a>
                </div>
            </div>
            <div class="table">
                
                <table>
                    <tr class="table-head">
                        <th><p class="table-head">No.</p></th>
                        <th><p class="table-head">Perubahan Terakhir</p></th>
                        <th><p class="table-head">Nama Item</p></th>
                        <th><p class="table-head">Deskripsi Barang</p></th>
                        <th><p class="table-head">Sisa Stock</p></th>
                        <th><p class="table-head">Harga Satuan</p></th>
                        <th><p class="table-head">Action</p></th>
                    </tr>
                    {% if products|length > 0 %}
                        {% for item in products %}
                        <tr class="table-content" style="background-color: #ffffff;">
                            <td><p class="table-content">{{ item.no }}</p></td>
                            <td><p class="table-content">{{ item.date }}</p></td>
                            <td><p class="table-content">{{ item.name }}</p></td>
                            <td><p class="table-content">{{ item.description }}</p></td>
                            <td style="display: flex; flex-direction: row; justify-content: center; align-items: center; background-color: #ffffff;">
                                <a href="{% url 'main:decrement_amount' item.pk %}" style="display: flex; align-items: center; justify-content: center; background-color: #ffffff; text-decoration: none; padding: 8px;">
                                    <i class="fa fa-minus" aria-hidden="true" style="color: #0195eb; background-color: #ffffff; padding: 4px; border-radius: 2px; text-decoration: none; border-style: none; border-color: #0195eb;"></i>
                                </a>
                                <p class="table-content" style="width: 100%;">{{ item.amount }}</p>
                                <a href="{% url 'main:increment_amount' item.pk %}" style="display: flex; align-items: center; justify-content: center; background-color: #ffffff; text-decoration: none; padding: 8px;">
                                    <i class="fa fa-plus" aria-hidden="true" style="color: #0195eb; background-color: #ffffff; padding: 4px; border-radius: 2px; text-decoration: none; border-style: none; border-color: #0195eb;"></i>
                                </a>
                            </td>
                            <td><p class="table-content">{{ item.price }}</p></td>
                            <td style="display: flex; flex-direction: row; justify-content: center; align-items: center;">
                                <div class="action-group" style="padding-inline: 8px; padding-block: 16px; border-radius: 20px; background-color: #ffffff; display: flex; flex-direction: row;">
                                    <a href="{% url 'main:delete_product' item.pk %}" style="display: flex; align-items: center; justify-content: center; background-color: white;">
                                        <i class="fa fa-trash" aria-hidden="true" style="color: #e24c1d; background-color: #ffd7cb; border-radius: 12px; width: 20px; height: 20px; display: flex; align-items: center; justify-content: center; padding: 4px; margin: 8px;"></i>
                                    </a>
                                    <a href="{% url 'main:edit_product' item.pk %}" style="display: flex; align-items: center; justify-content: center; background-color: white;">
                                        <i class="fa fa-edit" aria-hidden="true" style="color: #ffffff; background-color: #0195eb; border-radius: 12px; width: 20px; height: 20px; display: flex; align-items: center; justify-content: center; padding: 4px; margin: 8px;"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td style="height: 100%; display: flex; justify-content: center; align-items: center; padding-block: 200px;">Tidak ada produk yang tersedia</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            
                        </tr>
                    {% endif %}

                </table>
            </div>
            <!-- <div style="display: flex; flex-direction: row; justify-content: space-between; padding-top: 20px; background-color: rgb(241,241,241);">
                <div style="display: flex; flex-direction: row; justify-content: space-between; border-radius: 24px; align-items: center; width: 100%; padding: 20px; background-color: #ffffff;">
                    <h5 style="font-weight: 500; color: #b4b4b4; background-color: #ffffff;">Sesi terakhir login: {{ last_login }}</h5>
                    <a href="{% url 'main:logout' %}" style="background-color: #ffffff;">
                        <button style="background-color: #e24c1d; color: #ffffff;">
                            Logout
                        </button>
                    </a>
                    
                </div>
                
            </div> -->
        </div>
    </div>
</body>


{% endblock content %}

main/templates/navbar.html
{% extends 'base.html' %} 

{% block content %}

<div class="padding">
    <nav class="fullnav">
        <div class="menu-icon">
            <i class="fa fa-bars" aria-hidden="true" style="background-color: #ffffff; padding: 8px; border-radius: 12px; border-width: 2px; border-style: solid; border-color: rgb(241,241,241);" ></i>
        </div>
        <div class="logo">
            <!-- <img src="https://th.bing.com/th/id/R.6ad0fe976be696c1e6804c26a0b24e0c?rik=JF21H%2feXmlfXnQ&riu=http%3a%2f%2fmudvex.com%2fwp-content%2fuploads%2f2019%2f10%2flogo-12.png&ehk=H7KtZPbx18fPDvYg3nX7AfQ7vWFeNpZ9RcNSdNRKKrI%3d&risl=&pid=ImgRaw&r=0" alt="logo-brand"> -->
            <i class="fa-solid fa-cat" style="color: #ffffff; padding: 8px; border-radius: 8px; background-color: #e24c1d; margin-right: 8px;"></i>
            <p class="name">Mumu</p>
            <p class="name" style="color: #0195eb; font-weight: 800;">Miaw</p>
        </div>
        <div class="menu">
            <section class="menu-content">
                <a class="primary" href="#home">Tersedia</a>
                <a class="secondary" href="#home">Terjual</a>
            </section>
            <i class="fa-solid fa-bell" style="color: rgb(226, 76, 29); background-color: white;"></i>
            <span class="vertical-line">|
            </span>
            <div style="display: flex; flex-direction: column; background-color: #ffffff;">

                <div class="profile" style="width: 72%; display: flex; background-color: #ffffff;">
                    <a href="{% url 'main:dropdown_user' %}" style="display: flex; flex-direction: row; text-decoration: none; justify-content: space-between; align-items: center; background-color: #ffffff; color: black; width: 100%;">
                    <p class="user" style="background-color: white;">{{ name }}</p>
                    <i id="chevron" class="fa-solid fa-chevron-down" style="color: #b4b4b4; background-color: white; color: black; background-color: white;"></i>
                    <!-- <div class="dropdown-user" style="position: absolute; background-color: #ffffff; height: 172px; min-width: 0px; max-width: 400px; margin-top: 280px; margin-left: -100px; border-radius: 20px; border-color: #f0f0f0; border-style: solid; border-width: 2px; visibility: hidden;">
                        <a href="" style="background-color: #ffffff; width: 100%; justify-content: center;">
                            <button style="background-color: #ffffff; color: #888888; margin: 12px; justify-content: center; align-items: center; width: 86%; font-weight: 600; margin-right: 16px; justify-content: space-between;">
                                <i class="fa fa-user" aria-hidden="true" style="background-color: #ffffff; color: #0195eb; margin: 8px;"></i>
                                Profil Saya
                            </button>
                        </a>
                        <a href="{% url 'main:logout' %}" style="background-color: #ffffff; width: 100%; ">
                            <button style="background-color: #e24c1d; color: #ffffff; margin: 12px; justify-content: center; align-items: center; width: 88%;">
                                Logout
                            </button>
                        </a>
                    </div> -->
                    </a>
                
                </div>
                <div class="dropdown-user" style="position: absolute; background-color: #ffffff; height: 172px; min-width: 40px; max-width: 400px; margin-top: 80px; margin-left: -100px; border-radius: 20px; border-color: #f0f0f0; border-style: solid; border-width: 2px;">
                    <a href="" style="background-color: #ffffff; width: 100%; justify-content: center;">
                        <button style="background-color: #ffffff; color: #888888; margin: 12px; justify-content: center; align-items: center; width: 86%; font-weight: 600; margin-right: 16px; justify-content: space-between;">
                            <i class="fa fa-user" aria-hidden="true" style="background-color: #ffffff; color: #0195eb; margin: 8px;"></i>
                            Profil Saya
                        </button>
                    </a>
                    <a href="{% url 'main:logout' %}" style="background-color: #ffffff; width: 100%;">
                        <button style="background-color: #e24c1d; color: #ffffff; margin: 12px; justify-content: center; align-items: center; width: 88%;">
                            Logout
                        </button>
                    </a>
                </div>
            </div>
        </div>
        
    </nav> 
    </div>

    {% endblock content %}